### ISSUE TITLE
ld: cannot find -lbls384_256 on arm64 ubuntu 19.10.1

### ISSUE THREAD

**Issue by zven77** [herumi/bls-eth-go-binary#14]
Hello there!

I am currently trying to compile the Theta client (repository : https://github.com/thetatoken/theta-protocol-ledger ) on my Raspberry pi 4 4GB which is running on ubuntu 19.10.1 64bit version (https://ubuntu.com/download/raspberry-pi) 

Once I started the compile process with go 1.14.2 installed it stuck on the 'bls-eth-go-binary‘ part:

**ubuntu@ubuntu:~/go/src/github.com/thetatoken/theta$** make debug
go install -race ./cmd/...
'# github.com/herumi/bls-eth-go-binary/bls
/usr/bin/ld: cannot find -lbls384_256
collect2: error: ld returned 1 exit status
'#github.com/thetatoken/theta/crypto/bn256/cloudflare
crypto/bn256/cloudflare/gfp_arm64.s:109: illegal or missing addressing mode for symbol R18
asm: assembly of crypto/bn256/cloudflare/gfp_arm64.s failed
make: *** [Makefile:26: debug] Error 2

Well, the second lib (gfp_arm64.s) is the second challenge for me :))

I also started the test which Shigeo suggested:

go test -v ./bls
in the bls-eth-go-binary directory

This is the output:

=== RUN   TestAreAllMsgDifferent
--- PASS: TestAreAllMsgDifferent (0.00s)
=== RUN   Test
    Test: bls_test.go:285: i=0
    Test: bls_test.go:285: i=1
    Test: bls_test.go:285: i=2
    Test: bls_test.go:292: bad signature a0884dc424f077be5d6c4fdec36bc3d9a5fb349d2e20b6ed9ea9e16bf19182462869df333a04bb6a19861995270b49f415088ea97723d5fed062dcc2b379206b3cc8d04228e17e822d5726362df094b6f9937cdea8f79d48bcffea27ffffffff
    Test: bls_test.go:285: i=3
    Test: bls_test.go:285: i=4
    Test: bls_test.go:285: i=5
    Test: bls_test.go:285: i=6
    Test: bls_test.go:285: i=7
    Test: bls_test.go:292: bad signature b9195e62a9e171e9c5efb13328241ed35719b10f1efc036cbcb1269c89183cdedb2d9224927a32a31131cfb24bda1608081d2da6d53e431ada494f46c046131194661940ce31a83e1a1c76dccf75957113f290601ee93c7e0b7ce99dffffffff
    Test: bls_test.go:285: i=8
    Test: bls_test.go:307: blsAggregateVerifyNoCheckTestOne 1
    Test: bls_test.go:307: blsAggregateVerifyNoCheckTestOne 2
    Test: bls_test.go:307: blsAggregateVerifyNoCheckTestOne 15
    Test: bls_test.go:307: blsAggregateVerifyNoCheckTestOne 16
    Test: bls_test.go:307: blsAggregateVerifyNoCheckTestOne 17
    Test: bls_test.go:307: blsAggregateVerifyNoCheckTestOne 50
--- PASS: Test (5.87s)
PASS
ok  	_/home/ubuntu/work/bls-eth-go-binary/bls	5.878s

I saw on the github repository that you’ve added arm64 support and therefore it should be working. Do you have an idea how I could fix this problem?

Thank you for your support!
Sven

**Comment by herumi** [comment]
>I saw on the github repository that you’ve added arm64 support and therefore it should be working. Do you have an idea how I could fix this problem?

The `bls-eth-go-binary` used in Theta client seems old.
https://github.com/thetatoken/theta-protocol-ledger/blob/master/go.mod#L13
So would you mind asking the Theta team to update the list?

**Comment by zven77** [comment]
Thank you Shigeo! I think you can close this issue. 
I have informed one developer from the Theta team and because the change of the version number is rather sensible he asked me to change it locally and the compilation did not stop with the bls-eth-go-binary library.

I got the latest pseudo version number:

go get github.com/herumi/bls-eth-go-binary@latest
go: downloading github.com/herumi/bls-eth-go-binary v0.0.0-20200326062426-f58f8b8bd66f

and changed the required version in L13 locally:
/home/ubuntu/go/src/github.com/thetatoken/theta/go.mod

github.com/herumi/bls-eth-go-binary v0.0.0-20200107021104-147ed25f233e
changed to
github.com/herumi/bls-eth-go-binary v0.0.0-20200326062426-f58f8b8bd66f

…and it worked out. The compilation error didn’t came again during compilation.

**Comment by herumi** [comment]
Thank you for your information. I'm happy to hear that my library runs well on Raspberry pi 4.
