### ISSUE TITLE
 When I write an eth2.0 account related class, it can run normally, but when trying to package it into a mobile SDK, it reports the following error

### ISSUE THREAD

**Issue by MacOMNI** [herumi/bls-eth-go-binary#16]
When I write an eth2.0 account related class, it can run normally, but when trying to package it into a mobile SDK, it reports the following error
![image](https://user-images.githubusercontent.com/6373598/81281819-ec26ac00-908c-11ea-9757-b4f381533a5a.png)

**Comment by MacOMNI** [comment]
> When I write an eth2.0 account related class, it can run normally, but when trying to package it into a mobile SDK, it reports the following error
> ![image](https://user-images.githubusercontent.com/6373598/81281819-ec26ac00-908c-11ea-9757-b4f381533a5a.png)

the account is used bls-eth-go-binary to generate account ,like 
![image](https://user-images.githubusercontent.com/6373598/81282793-3eb49800-908e-11ea-94d4-f17b65c22576.png)

**Comment by MacOMNI** [comment]
How can I generate mobile sdk like android?

**Comment by herumi** [comment]
>error: cannot find -lbls384_256.a
The compiled binary is at https://github.com/herumi/bls-eth-go-binary/tree/master/bls/lib/android , and the position is specified at https://github.com/herumi/bls-eth-go-binary/blob/master/bls/bls.go#L7-L9 .
I'm sorry, I'm not familiar with gomobile.
So could you ask the community how to specify it?

**Comment by MacOMNI** [comment]
Yeah, How to generate bls privatekey through Seed
key ?

**Comment by MacOMNI** [comment]
Yeah, How to generate bls privatekey through 'Seed' or 'mnemonic' ?

**Comment by herumi** [comment]
Please use `SecretKey.SetLittleEndianMod()` for a generated byte array.
cf.  https://github.com/herumi/bls-wasm/issues/6#issuecomment-608362453

**Comment by MacOMNI** [comment]
ths,I will try.

**Comment by MacOMNI** [comment]
When I use   64bytes seed generated by bip39 ,error is "err blsSecretKeySetLittleEndianMod -1"

**Comment by MacOMNI** [comment]
as follow
![image](https://user-images.githubusercontent.com/6373598/81392800-c6afa600-9151-11ea-9cb1-35df2051a64e.png)

**Comment by herumi** [comment]
The following code runs well.

```
func main() {
    bls.Init(bls.BLS12_381)
    var sec bls.SecretKey
    b := make([]byte, 64)
    for i := 0; i < len(b); i++ {
        b[i] = 0xff
    }
    err := sec.SetLittleEndianMod(b)
    if err != nil {
        fmt.Printf("err")
        return
    }
    fmt.Printf("sec=%x\n", sec.Serialize())
}
```

Do you call `bls.Init(bls.BLS12_381)`?

**Comment by MacOMNI** [comment]
sorry, I forget it. It  runs well. ths

**Comment by herumi** [comment]
>https://github.com/herumi/bls-eth-go-binary/issues/16#issuecomment-625556344

Did the first problem of gomobile go away?

**Comment by MacOMNI** [comment]
NO , just iOS is ok. Andriod gomobile bind failed

**Comment by herumi** [comment]
As I mentioned, I'm not familiar with gomobile, then could you ask the community and give me feedback if you know about it?

**Comment by herumi** [comment]
[0chain/gosdk](https://github.com/0chain/gosdk) uses my library with gomobile. Could you check it?

**Comment by MacOMNI** [comment]
Is it possible to use bls-eth-go-library without compiling a static library like ios_xx.a, andriod_xx.a ? Because, I want to compile other cross-platform static libraries. Nesting static libraries in static libraries currently seems to cause some other problems.
