### ISSUE TITLE
blsVerifyAggregatedHashWithDomainCast?

### ISSUE THREAD

**Issue by prestonvanloon** [herumi/bls-eth-go-binary#17]
What is the purpose of this inline function casting for production code? 

https://github.com/herumi/bls-eth-go-binary/blob/5d07558bf3edad945df95e0b4339ac904fe91086/bls/bls.go#L19-L24

We're having a minor difficulty with inline cgo functions in our build tooling. 
Can this be removed?

**Comment by herumi** [comment]
It is for testing on Travis-ci.
The detail is https://github.com/herumi/bls-eth-go-binary/issues/13 .

I have two choices.
- Give up on testing with Linux on Travis-ci.
- `blsVerifyAggregatedHashWithDomain` is for an old Ethereum spec, then remove these apis.

What do you think?

**Comment by prestonvanloon** [comment]
I don't think giving up on travis is a great solution. If it's not being used, we could remove VerifyAggregateHashWithDomain as you suggested. I confirmed in Prysm that we are not using this method. Thanks

**Comment by herumi** [comment]
>https://github.com/herumi/bls-eth-go-binary/pull/18

Can I remove the other APIs such as `SignHashWithDomain`, `VerifyHashWithDomain`?

**Comment by prestonvanloon** [comment]
@herumi sounds good, we don’t use those methods. 

Also, my PR is failing, I think I forgot to delete some tests. I’ll fix it tomorrow.

**Comment by herumi** [comment]
Okay, I'll fix it, so you don't have to fix the PR.

**Comment by herumi** [comment]
I've removed them.
https://github.com/herumi/bls-eth-go-binary/commit/01d282b5380b0b0a59a880a2a645143807595ff3

**Comment by prestonvanloon** [comment]
Thank you!
