### ISSUE TITLE
Update headers and precompiled archives

### ISSUE THREAD

**Issue by prestonvanloon** [herumi/bls-eth-go-binary#19]
Hey @herumi, could you update the header files and the precompiled archives with the latest changes? 

Thanks!

**Comment by herumi** [comment]
Removing `hashWithDomain` of cgo does not affect binary, so it is not necessary to update static libraries.
I'll update the header later after updating the other language bindings.

**Comment by prestonvanloon** [comment]
Do the current archives support draft 07 of hash to curve?

**Comment by prestonvanloon** [comment]
Actually nevermind, I was looking at an old commit. I see it was updated 8 days ago. I'll go ahead and close this since it's not an issue. Thanks!
