### ISSUE TITLE
Failed to build on Windows

### ISSUE THREAD

**Issue by moshababo** [herumi/bls-eth-go-binary#2]
Hi, 
In testing the cross-platform support of the lib, I failed to build it on Windows.
Was it ever tested?

Here's the log output:

```
$ go get github.com/herumi/bls-eth-go-binary

C:\Users\...\AppData\Local\Temp\go-build565733454\b032\_x002.o: In function `_cgo_f3aafd9c2291_Cfunc_blsPublicKeyDeserializeUncompressed':
/tmp/go-build/cgo-gcc-prolog:330: undefined reference to `blsPublicKeyDeserializeUncompressed'
C:\Users\...\AppData\Local\Temp\go-build565733454\b032\_x002.o: In function `_cgo_f3aafd9c2291_Cfunc_blsPublicKeySerializeUncompressed':
/tmp/go-build/cgo-gcc-prolog:432: undefined reference to `blsPublicKeySerializeUncompressed'
C:\Users\...\AppData\Local\Temp\go-build565733454\b032\_x002.o: In function `_cgo_f3aafd9c2291_Cfunc_blsSignHashWithDomain':
/tmp/go-build/cgo-gcc-prolog:806: undefined reference to `blsSignHashWithDomain'
C:\Users\...\AppData\Local\Temp\go-build565733454\b032\_x002.o: In function `_cgo_f3aafd9c2291_Cfunc_blsSignatureDeserializeUncompressed':
/tmp/go-build/cgo-gcc-prolog:859: undefined reference to `blsSignatureDeserializeUncompressed'
C:\Users\...\AppData\Local\Temp\go-build565733454\b032\_x002.o: In function `_cgo_f3aafd9c2291_Cfunc_blsSignatureSerializeUncompressed':
/tmp/go-build/cgo-gcc-prolog:961: undefined reference to `blsSignatureSerializeUncompressed'
C:\Users\...\AppData\Local\Temp\go-build565733454\b032\_x002.o: In function `_cgo_f3aafd9c2291_Cfunc_blsVerifyAggregatedHashWithDomain':
/tmp/go-build/cgo-gcc-prolog:1026: undefined reference to `blsVerifyAggregatedHashWithDomain'
C:\Users\...\AppData\Local\Temp\go-build565733454\b032\_x002.o: In function `_cgo_f3aafd9c2291_Cfunc_blsVerifyHashWithDomain':
/tmp/go-build/cgo-gcc-prolog:1092: undefined reference to `blsVerifyHashWithDomain'
C:/Users/…/go/src/github.com/herumi/bls-eth-go-binary/bls/lib/windows/amd64/libbls384_256.a(fp.o):fp.cpp:(.text$_ZN3mcl2fp11FpGenerator13gen_addSubPreEbi[_ZN3mcl2fp11FpGenerator13gen_addSubPreEbi]+0x30b): undefined reference to `__imp___acrt_iob_func'
C:/Users/.../go/src/github.com/herumi/bls-eth-go-binary/bls/lib/windows/amd64/libbls384_256.a(fp.o):fp.cpp:(.text$_ZN3mcl2fp11FpGenerator13gen_addSubPreEbi[_ZN3mcl2fp11FpGenerator13gen_addSubPreEbi]+0x373): undefined reference to `__imp___acrt_iob_func'
C:/Users/.../go/src/github.com/herumi/bls-eth-go-binary/bls/lib/windows/amd64/libbls384_256.a(fp.o):fp.cpp:(.text$_ZN3mcl2fp11FpGenerator13gen_addSubPreEbi[_ZN3mcl2fp11FpGenerator13gen_addSubPreEbi]+0x3db): undefined reference to `__imp___acrt_iob_func'
C:/Users/.../go/src/github.com/herumi/bls-eth-go-binary/bls/lib/windows/amd64/libbls384_256.a(fp.o):fp.cpp:(.text$_ZN3mcl2fp11FpGenerator13gen_addSubPreEbi[_ZN3mcl2fp11FpGenerator13gen_addSubPreEbi]+0x443): undefined reference to `__imp___acrt_iob_func'
C:/Users/.../go/src/github.com/herumi/bls-eth-go-binary/bls/lib/windows/amd64/libbls384_256.a(fp.o):fp.cpp:(.text$_ZN3mcl2fp11FpGenerator13gen_addSubPreEbi[_ZN3mcl2fp11FpGenerator13gen_addSubPreEbi]+0x51e): undefined reference to `__imp___acrt_iob_func'
C:/Users/.../go/src/github.com/herumi/bls-eth-go-binary/bls/lib/windows/amd64/libbls384_256.a(fp.o):fp.cpp:(.text$_ZN3mcl2fp11FpGenerator13gen_addSubPreEbi[_ZN3mcl2fp11FpGenerator13gen_addSubPreEbi]+0x617): more undefined references to `__imp___acrt_iob_func' follow
collect2.exe: error: ld returned 1 exit status
```

**Comment by herumi** [comment]
Thank you for the report. I'm sorry that I forgot to push the windows binary.
I've updated it now. Could you try the latest version?

**Comment by avive** [comment]
@herumi - there's still a build issue with the new binary. Here's what we are getting with the latest version:

`C:\Users\Spacemesher\go\src\github.com\herumi\bls-eth-go-binary>go get
# github.com/herumi/bls-eth-go-binary/bls
C:/Users/Spacemesher/go/src/github.com/herumi/bls-eth-go-binary/bls/lib/windows/amd64/libbls384_256.a(fp.o):fp.cpp:(.text$_ZN3mcl2fp11FpGenerator13gen_addSubPreEbi[_ZN3mcl2fp11FpGenerator13gen_addSubPreEbi]+0x30f): undefined reference to `__imp___acrt_iob_func'
C:/Users/Spacemesher/go/src/github.com/herumi/bls-eth-go-binary/bls/lib/windows/amd64/libbls384_256.a(fp.o):fp.cpp:(.text$_ZN3mcl2fp11FpGenerator13gen_addSubPreEbi[_ZN3mcl2fp11FpGenerator13gen_addSubPreEbi]+0x377): undefined reference to `__imp___acrt_iob_func'
C:/Users/Spacemesher/go/src/github.com/herumi/bls-eth-go-binary/bls/lib/windows/amd64/libbls384_256.a(fp.o):fp.cpp:(.text$_ZN3mcl2fp11FpGenerator13gen_addSubPreEbi[_ZN3mcl2fp11FpGenerator13gen_addSubPreEbi]+0x3df): undefined reference to `__imp___acrt_iob_func'
C:/Users/Spacemesher/go/src/github.com/herumi/bls-eth-go-binary/bls/lib/windows/amd64/libbls384_256.a(fp.o):fp.cpp:(.text$_ZN3mcl2fp11FpGenerator13gen_addSubPreEbi[_ZN3mcl2fp11FpGenerator13gen_addSubPreEbi]+0x447): undefined reference to `__imp___acrt_iob_func'
C:/Users/Spacemesher/go/src/github.com/herumi/bls-eth-go-binary/bls/lib/windows/amd64/libbls384_256.a(fp.o):fp.cpp:(.text$_ZN3mcl2fp11FpGenerator13gen_addSubPreEbi[_ZN3mcl2fp11FpGenerator13gen_addSubPreEbi]+0x5c6): undefined reference to `__imp___acrt_iob_func'
C:/Users/Spacemesher/go/src/github.com/herumi/bls-eth-go-binary/bls/lib/windows/amd64/libbls384_256.a(fp.o):fp.cpp:(.text$_ZN3mcl2fp11FpGenerator13gen_addSubPreEbi[_ZN3mcl2fp11FpGenerator13gen_addSubPreEbi]+0x6bf): more undefined references to `__imp___acrt_iob_func' follow
collect2.exe: error: ld returned 1 exit status`

**Comment by herumi** [comment]
Hum, there is no errors on my environment.
I uses Go on MINGW64.
```
$ go version
go version go1.12.4 windows/amd64
$ gcc --version
gcc.exe (Rev2, Built by MSYS2 project) 8.3.0
/c/Users/shigeo/go/src/github.com/herumi/bls-eth-go-binary
$ git br -v
* master 147ed25 update windows binary
go run sample.go
...
verify=true
```
I found https://github.com/racer-rust/racer/issues/919 . Do you use the older gcc?

**Comment by avive** [comment]
We tried with both gcc from cygwin and from mingw64 (latest distros). Our gcc versions are lower. Can you please share what distro of mingw64 you are using to gcc v 8.3.0 ?

**Comment by avive** [comment]
Thank you for the info. The problem was indeed usage of an old version of gcc. Getting gcc via mingw64 and your updated binary does the trick. You can close this issue. Thank you again for this wonderful library.

**Comment by herumi** [comment]
Okay.
