### ISSUE TITLE
How to cross-compile

### ISSUE THREAD

**Issue by eabz** [herumi/bls-eth-go-binary#20]
Hello @herumi thanks for your awesome bls library.
I am using it on a golang project and I need to build a cross-compile script. 
Just want to ask how can I enable the static lib change using `GOOS` and `GOARCH` or if I need to override the lib path.

Thanks

**Comment by herumi** [comment]
I'm sorry that I could not understand your question.

This library supports `#cgo GOOS,GOARCH` described at https://github.com/herumi/bls-eth-go-binary/blob/master/bls/bls.go#L7-L14 .

**Comment by MacOMNI** [comment]
Is it possible to use bls-eth-go-library without compiling a static library like ios_xx.a, andriod_xx.a ? Because, I want to compile other cross-platform static libraries. Nesting static libraries in static libraries currently seems to cause some other problems.

**Comment by eabz** [comment]
Sorry, my mistake. Didn't know I have to pass the entire toolchain. 
Now I am able to cross-compile.
