### ISSUE TITLE
Build on Raspberry Pi Raspbian not working

### ISSUE THREAD

**Issue by jooray** [herumi/bls-eth-go-binary#23]
```
$ GO111MODULE=on go get github.com/wealdtech/ethdo
...
# github.com/herumi/bls-eth-go-binary/bls
/usr/bin/ld: $WORK/b268/_x004.o: in function `_cgo_0a6001f6c098_Cfunc_mclBn_setOriginalG2cofactor':
/tmp/go-build/cgo-gcc-prolog:2323: undefined reference to `mclBn_setOriginalG2cofactor'
collect2: error: ld returned 1 exit status
```

That's after building mcl and bls libraries. If I don't build them, I get:

```
GO111MODULE=on go get github.com/wealdtech/ethdo
go: github.com/wealdtech/ethdo upgrade => v1.4.22
# github.com/herumi/bls-eth-go-binary/bls
/usr/bin/ld: cannot find -lbls384_256
collect2: error: ld returned 1 exit status
```

which is probably understandable.

**Comment by herumi** [comment]
Does `Raspberry Pi` mean 32-bit arm?

wealdtech shows `go: downloading github.com/herumi/bls-eth-go-binary v0.0.0-20200621110855-298ffb6847bc`.

Could you update `bls-eth-go-binary` to the latest version?

**Comment by jooray** [comment]
I tried to install 64-bit Ubuntu LTS on Raspberry Pi and everything works, this might be related to 32-bit ARM though.
