### ISSUE TITLE
Possible memory leak with blsInit

### ISSUE THREAD

**Issue by prestonvanloon** [herumi/bls-eth-go-binary#24]
Our fuzz testing with ASAN is reporting the following leak.

```
  | Direct leak of 16384 byte(s) in 1 object(s) allocated from:
-- | --
  | #0 0x60ba1d in malloc _asan_rtl_:3
  | #1 0x1180c4d in mcl::Array<unsigned long>::resize(unsigned long)
  | #2 0x1032214 in mcl::fp::Op::init(mcl::VintT<mcl::vint::FixedBuffer<unsigned long, 768ul> > const&, unsigned long, int, mcl::fp::Mode, unsigned long)
  | #3 0xf87129 in mcl::FpT<mcl::bn::local::FrTag, 256ul>::init(bool*, int, mcl::VintT<mcl::vint::FixedBuffer<unsigned long, 768ul> > const&, mcl::fp::Mode)
  | #4 0xf936e0 in mcl::bn::local::Param::init(bool*, mcl::CurveParam const&, mcl::fp::Mode)
  | #5 0xf6cdc8 in blsInit
  | #6 0xf474ee in _cgo_592780cd2cc3_Cfunc_blsInit
  | #7 0x698037 in runtime.asmcgocall
```

This issue isn't reliably reproduced, so it may not be a factor. It's only appeared once in our fuzz testing, but I wanted to bring to your attention just in case. 

Do you think this is a valid issue?

**Comment by herumi** [comment]
Could you tell me the arguments which were passed to blsInit?
I expect that a user application passes correct arguments to `blsInit` so I'll check it again.
If `blsInit` successes, then the test with address sanitizer (-fsanitize=address) does not report any problem.
https://travis-ci.org/github/herumi/mcl/jobs/709817761

**Comment by prestonvanloon** [comment]
Thanks for looking into it so quickly. We call bls.Init here: https://github.com/prysmaticlabs/prysm/blob/fb8be4d555dd67e091c5740fe48f568599a94d48/shared/bls/herumi/init.go#L6

```go
package herumi

import "github.com/herumi/bls-eth-go-binary/bls"

func init() {
	if err := bls.Init(bls.BLS12_381); err != nil {
		panic(err)
	}
	if err := bls.SetETHmode(bls.EthModeDraft07); err != nil {
		panic(err)
	}
}
```

**Comment by herumi** [comment]
Oh, I'm sorry for my misunderstanding.
`bls.Init` and `mcl::initPairing` use static variables in their functions.
Those destructors will be called after finishing `main`. But they will not be called from cgo, so it seems leaks. I don't think that it is wrong.

I make a tiny sample at https://github.com/herumi/misc/tree/master/go/cstr .
The function `cstr()` is defined at https://github.com/herumi/misc/blob/master/go/cstr/cstr.cpp .
If it is called from [main.cpp](https://github.com/herumi/misc/blob/master/go/cstr/main.cpp), it shows:

```
% ./main
main
X cstr
end
X dstr
```
`X dstr` is called then there is no leak.
But if it is called from [cstr.go](https://github.com/herumi/misc/blob/master/go/cstr/cstr.go), then the destructor will not be called.

```
% go run cstr.go
call C.cstr
X cstr
end
```

**Comment by prestonvanloon** [comment]
Thanks for confirming. Is this issue OK to close or is there some action we can take?

Is 16384 bytes expected? That seems like a high amount

**Comment by herumi** [comment]
mcl initializes many lookup tables, so it requires many memory.
For example, [op.invTbl.resize](https://github.com/herumi/mcl/blob/master/src/fp.cpp#L371) requires  N * sizeof(Unit) * 8 * 2 * N * sizeof(uint64_t) = 4 * 8 * 8 * 2 * 4 * 8 = 16384 bytes.

**Comment by prestonvanloon** [comment]
Thanks! It sounds like this is expected and we can ignore this fizzier report. We appreciate the quick attention. 😀
