### ISSUE TITLE
Which version of mcl, bls library should I use?

### ISSUE THREAD

**Issue by egonspace** [herumi/bls-eth-go-binary#28]
I'm sorry for posting the question, not the issue.

We are using `bls-eth-go-binary` of which version is v0.0.0-20200522010937-01d282b5380b
However, if we use that binary on an alpine-linux, a segment fault error occurred, so we are building the library ourselves.

To build this library, we need to download the mcl and bls source code together, but the problem is which version should we use.
The version we tried is as follows.

bls-eth-go-binary: 01d282b5380b0b0a59a880a2a645143807595ff3.
bls: accfc25c06c017f2686bb59c5106655293dd47d3
mcl: d51fd79c86954a443b1c7ce67d7bcdb8a63ddedb

But this version doesn't seem to fit together. Segment fault occurs during execution.

Could you tell me which versions of mcl and bls were used by the binaries in the bls-eth-go-binary?

**Comment by herumi** [comment]
>which version is v0.0.0-20200522010937-01d282b5380b

It seems too old. Could you try the latest version?

I made the library as the following:
```
mcl, bls, bls-eth-go-binary are all origin/master
mcl ; 0e64636
bls ; e466375
bls-eth-go-binary ; 32b29e5

Ubuntu 20.04.1 LTS
clang version 10.0.0-4ubuntu1

>cd bls-eth-go-binary
>make CXX=clang++-10
>go test ./bls
>ok      github.com/herumi/bls-eth-go-binary/bls
```

**Comment by egonspace** [comment]
The latest version didn't have a tag, so I used the last version of the tag. Thank you for letting me know.

**Comment by herumi** [comment]
Thank you for your suggestion. I've tagged it now.
