### ISSUE TITLE
bls.SecretKey SignHash return nil

### ISSUE THREAD

**Issue by alphaqiu** [herumi/bls-eth-go-binary#3]
```
func main() {
	bls.Init(bls.BLS12_381)
	var key bls.SecretKey
	key.SetByCSPRNG()


	sig := key.SignHash([]byte("Hello World"))
	fmt.Println(sig)
        // Output: <nil>
        // expect signature obj
}
```

**Comment by herumi** [comment]
I'm sorry for my poor document.
`SignHash` and `VerifyHash` functions take only hashed value which can be deserialized to `Fp2`.

Could you use `SignHashWithDomain` and `VerifyHashWithDomain` intead of them?
see https://github.com/herumi/bls/#ethereum-20-spec-mode

Or you can use
```
s := sec.Sign("hello")
fmt.Printf("verify=%v\n", s.Verify(pub, "hello"))
fmt.Printf("verify=%v\n", s.Verify(pub, "hellr"))
```
But the specification is not compatible with Ethereum.
