### ISSUE TITLE
Add Relevant Commits For Precompiled Archives

### ISSUE THREAD

**Issue by nisdas** [herumi/bls-eth-go-binary#30]
Currently precompiled archives are checked into the repo, however there is no way to know which specific commit of 
https://github.com/herumi/bls or https://github.com/herumi/mcl is used when creating those specific archives. It will be very 
useful for consumers of this library to know those commits as it makes it easier when building everything from source. Otherwise, the current approach right now would would be to simply just take the latest master of both `herumi/bls` or `herumi/mcl`.

**Comment by herumi** [comment]
Okay. I'll describe the branch that built the library from the next.
