### ISSUE TITLE
Current Android Precompiled Archives Out Of Date

### ISSUE THREAD

**Issue by nisdas** [herumi/bls-eth-go-binary#32]
https://github.com/herumi/bls-eth-go-binary/tree/master/bls/lib/android 

The current archives are 5 months old and have not been updated to the latest version. This came up as we were use the android archives for our `aarch64` builds. However we did  eventually run into issues with missing symbols due to it being out of date. We have switched out to the arm64 archive in the linux sub-directory and it has fixed our issue. 

https://github.com/herumi/bls-eth-go-binary/tree/master/bls/lib/linux/arm64

**Comment by herumi** [comment]
Thank you for the pointout.
Is it okay https://github.com/herumi/bls-eth-go-binary/commit/11b716565c1c95338de4056daee6001d3dc2482c ?

**Comment by nisdas** [comment]
Sounds good thanks :+1:
