### ISSUE TITLE
please add the iOS lib to the github repo thanks

### ISSUE THREAD

**Issue by hopwesley** [herumi/bls-eth-go-binary#36]
# github.com/herumi/bls-eth-go-binary/bls
ld: warning: directory not found for option '-L/var/folders/pd/zfbdf6sj5w53r8lwf723pfgw0000gn/T/gomobile-work-029037962/pkg/mod/github.com/herumi/bls-eth-go-binary@v0.0.0-20210325004959-a24496ac0743/bls/lib/ios'
ld: warning: directory not found for option '-L/var/folders/pd/zfbdf6sj5w53r8lwf723pfgw0000gn/T/gomobile-work-029037962/pkg/mod/github.com/herumi/bls-eth-go-binary@v0.0.0-20210325004959-a24496ac0743/bls/lib/darwin/arm64'
ld: library not found for -lbls384_256
clang: error: linker command failed with exit code 1 (use -v to see invocation)
gomobile: darwin-arm64: go build -tags ios -v -buildmode=c-archive -o /var/folders/pd/zfbdf6sj5w53r8lwf723pfgw0000gn/T/gomobile-work-029037962/iosLib-arm64.a ./gobind failed: exit status 2

**Comment by hopwesley** [comment]
package bls

/*
#cgo CFLAGS:-I${SRCDIR}./include -DBLS_ETH -DBLS_SWAP_G
#cgo LDFLAGS:-lbls384_256 -lstdc++ -lm
**#cgo ios LDFLAGS:-L${SRCDIR}/lib/ios**
#cgo android,arm64 LDFLAGS:-L${SRCDIR}/lib/linux/arm64
#cgo android,arm LDFLAGS:-L${SRCDIR}/lib/android/armeabi-v7a
#cgo android,amd64 LDFLAGS:-L${SRCDIR}/lib/linux/amd64

**Comment by hopwesley** [comment]
# github.com/herumi/bls-eth-go-binary/bls
ld: error: unable to find library -lbls384_256
clang: error: linker command failed with exit code 1 (use -v to see invocation)
gomobile: go build -v -buildmode=c-shared -o=/var/folders/pd/zfbdf6sj5w53r8lwf723pfgw0000gn/T/gomobile-work-418295603/android/src/main/jniLibs/x86/libgojni.so ./gobind failed: exit status 2

**Comment by herumi** [comment]
I don't commit ios binary, so could you `make ios` to build it before `go build`?

**Comment by hopwesley** [comment]
> I don't commit ios binary, so could you `make ios` to build it before `go build`?

I can build iOS binary ,but how to remove the err when using gomobile , I can't remove following line:
#cgo ios LDFLAGS:-L${SRCDIR}/lib/iOS
this code make the gomobile link the lib every time I build my own lib, and gomobile create a new directory every time.
so even I put the iOS lib into the right directory , gomobile doesn't use it and just create a new one.
I want to commit a iOS binary
I have fork this and commit it by my own repo :https://github.com/ninjahome/bls-wallet
can I merge it into this project ?

**Comment by hopwesley** [comment]
please merge my brach please

**Comment by herumi** [comment]
I want to restrict the kind of binary to put because it increases repository size.
So then could you please fork and put them as you have already done?

**Comment by hopwesley** [comment]
I have forked the git repo, but there are still link errors for iOS please check my issues

**Comment by hopwesley** [comment]
how to use this repo in iOS https://github.com/herumi/cybozulib
I foud the Xcode error is about 
  "vtable for __cxxabiv1::__si_class_type_info", referenced from:
      typeinfo for cybozu::Exception in libbls384_256.a(bls_c384_256.o)
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "typeinfo for std::exception", referenced from:
      typeinfo for cybozu::Exception in libbls384_256.a(bls_c384_256.o)

**Comment by herumi** [comment]
See https://github.com/herumi/bls-eth-go-binary/issues/41
