### ISSUE TITLE
android build err

### ISSUE THREAD

**Issue by hopwesley** [herumi/bls-eth-go-binary#37]
make[1]: Entering directory '/Users/hyperorchid/xcodedata/2/bls-wallet/android/jni'
[arm64-v8a] Compile++      : bls384_256 <= bls_c384_256.cpp
In file included from/../../src/bls/src/bls_c384_256.cpp:3:
In file included from../../src/bls/src/bls_c_impl.hpp:6:
./../src/bls/include/bls/bls.h:10:10: fatal error: 'mcl/bn.h' file not found
#include <mcl/bn.h>

**Comment by hopwesley** [comment]
ndk-build -v
GNU Make 4.3.90
Built for x86_64-apple-darwin
Copyright (C) 1988-2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

**Comment by hopwesley** [comment]
ifeq ($(MY_BIT),64)
  MY_BASE_LL := $(LOCAL_PATH)/../../src/bls/mcl/src/base64.ll
  LOCAL_CPPFLAGS += -DMCL_SIZEOF_UNIT=8
endif
ifeq ($(MY_BIT),32)
  MY_BASE_LL := $(LOCAL_PATH)/../../src/bls/mcl/src/base32.ll
  LOCAL_CPPFLAGS += -DMCL_SIZEOF_UNIT=4
endif
LOCAL_SRC_FILES :=  $(LOCAL_PATH)/../../src/bls/src/bls_c384_256.cpp $(LOCAL_PATH)/../../src/bls/mcl/src/fp.cpp $(MY_BASE_LL)
LOCAL_C_INCLUDES := $(LOCAL_PATH)/../../src/bls/include $(LOCAL_PATH)/../../src/bls/mcl/include

**Comment by hopwesley** [comment]
the mcl directory is a subdirectory of bls, so please change the make file :Android.mk

**Comment by herumi** [comment]
Thanks for letting me know. I've fixed it at https://github.com/herumi/bls-eth-go-binary/commit/874c3f761283540b6f369f52f94e0cfa78d316a2 .
