### ISSUE TITLE
iOS link failed

### ISSUE THREAD

**Issue by hopwesley** [herumi/bls-eth-go-binary#41]
Undefined symbols for architecture x86_64:
  "vtable for __cxxabiv1::__si_class_type_info", referenced from:
      typeinfo for cybozu::Exception in libbls384_256.a(bls_c384_256.o)
      typeinfo for cybozu::Exception in libbls384_256.a(fp.o)
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "typeinfo for std::exception", referenced from:
      typeinfo for cybozu::Exception in libbls384_256.a(bls_c384_256.o)
      typeinfo for cybozu::Exception in libbls384_256.a(fp.o)
  "std::__1::__thread_local_data()", referenced from:
      void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(mclBnGT*, blsSignature*, blsSignature const*, blsPublicKey const*, char const*, unsigned long, char const*, unsigned long, unsigned long), mclBnGT*, blsSignature*, blsSignature const*, blsPublicKey const*, char const*, unsigned long, char const*, unsigned long, unsigned long> >(void*) in libbls384_256.a(bls_c384_256.o)
  "std::__1::__thread_struct::__thread_struct()", referenced from:
      std::__1::thread::thread<void (&)(mclBnGT*, blsSignature*, blsSignature const*, blsPublicKey const*, char const*, unsigned long, char const*, unsigned long, unsigned long), mclBnGT*, blsSignature*, blsSignature const*&, blsPublicKey const*&, char const*&, unsigned long&, char const*&, unsigned long&, unsigned long&, void>(void (&)(mclBnGT*, blsSignature*, blsSignature const*, blsPublicKey const*, char const*, unsigned long, char const*, unsigned long, unsigned long), mclBnGT*&&, blsSignature*&&, blsSignature const*&, blsPublicKey const*&, char const*&, unsigned long&, char const*&, unsigned long&, unsigned long&) in libbls384_256.a(bls_c384_256.o)
  "operator new(unsigned long)", referenced from:
      std::__1::thread::thread<void (&)(mclBnGT*, blsSignature*, blsSignature const*, blsPublicKey const*, char const*, unsigned long, char const*, unsigned long, unsigned long), mclBnGT*, blsSignature*, blsSignature const*&, blsPublicKey const*&, char const*&, unsigned long&, char const*&, unsigned long&, unsigned long&, void>(void (&)(mclBnGT*, blsSignature*, blsSignature const*, blsPublicKey const*, char const*, unsigned long, char const*, unsigned long, unsigned long), mclBnGT*&&, blsSignature*&&, blsSignature const*&, blsPublicKey const*&, char const*&, unsigned long&, char const*&, unsigned long&, unsigned long&) in libbls384_256.a(bls_c384_256.o)
  "std::__1::__thread_struct::~__thread_struct()", referenced from:
      std::__1::thread::thread<void (&)(mclBnGT*, blsSignature*, blsSignature const*, blsPublicKey const*, char const*, unsigned long, char const*, unsigned long, unsigned long), mclBnGT*, blsSignature*, blsSignature const*&, blsPublicKey const*&, char const*&, unsigned long&, char const*&, unsigned long&, unsigned long&, void>(void (&)(mclBnGT*, blsSignature*, blsSignature const*, blsPublicKey const*, char const*, unsigned long, char const*, unsigned long, unsigned long), mclBnGT*&&, blsSignature*&&, blsSignature const*&, blsPublicKey const*&, char const*&, unsigned long&, char const*&, unsigned long&, unsigned long&) in libbls384_256.a(bls_c384_256.o)
      void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(mclBnGT*, blsSignature*, blsSignature const*, blsPublicKey const*, char const*, unsigned long, char const*, unsigned long, unsigned long), mclBnGT*, blsSignature*, blsSignature const*, blsPublicKey const*, char const*, unsigned long, char const*, unsigned long, unsigned long> >(void*) in libbls384_256.a(bls_c384_256.o)
  "___cxa_allocate_exception", referenced from:
      cybozu::RandomGenerator::RandomGenerator() in libbls384_256.a(bls_c384_256.o)
      cybozu::RandomGenerator::RandomGenerator() in libbls384_256.a(fp.o)
  "___cxa_throw", referenced from:
      cybozu::RandomGenerator::RandomGenerator() in libbls384_256.a(bls_c384_256.o)
      cybozu::RandomGenerator::RandomGenerator() in libbls384_256.a(fp.o)
  "std::__1::__throw_system_error(int, char const*)", referenced from:
      std::__1::thread::thread<void (&)(mclBnGT*, blsSignature*, blsSignature const*, blsPublicKey const*, char const*, unsigned long, char const*, unsigned long, unsigned long), mclBnGT*, blsSignature*, blsSignature const*&, blsPublicKey const*&, char const*&, unsigned long&, char const*&, unsigned long&, unsigned long&, void>(void (&)(mclBnGT*, blsSignature*, blsSignature const*, blsPublicKey const*, char const*, unsigned long, char const*, unsigned long, unsigned long), mclBnGT*&&, blsSignature*&&, blsSignature const*&, blsPublicKey const*&, char const*&, unsigned long&, char const*&, unsigned long&, unsigned long&) in libbls384_256.a(bls_c384_256.o)
  "___cxa_guard_abort", referenced from:
      mcl::FpT<mcl::bn::local::FrTag, 256ul>::setByCSPRNG(bool*, mcl::fp::RandGen) in libbls384_256.a(bls_c384_256.o)
      mcl::FpT<mcl::bn::local::FpTag, 384ul>::setByCSPRNG(bool*, mcl::fp::RandGen) in libbls384_256.a(bls_c384_256.o)
      mcl::fp::RandGen::setRandFunc(void*, unsigned int (*)(void*, void*, unsigned int)) in libbls384_256.a(bls_c384_256.o)
      mcl::fp::RandGen::getDefaultRandGen() in libbls384_256.a(bls_c384_256.o)
      mcl::VintT<mcl::vint::FixedBuffer<unsigned long long, 1024ul> >::setRand(bool*, mcl::VintT<mcl::vint::FixedBuffer<unsigned long long, 1024ul> > const&, mcl::fp::RandGen) in libbls384_256.a(fp.o)
      mcl::fp::RandGen::getDefaultRandGen() in libbls384_256.a(fp.o)
  "std::exception::~exception()", referenced from:
      cybozu::RandomGenerator::RandomGenerator() in libbls384_256.a(bls_c384_256.o)
      cybozu::Exception::~Exception() in libbls384_256.a(bls_c384_256.o)
      cybozu::Exception::~Exception() in libbls384_256.a(bls_c384_256.o)
      cybozu::RandomGenerator::RandomGenerator() in libbls384_256.a(fp.o)
      cybozu::Exception::~Exception() in libbls384_256.a(fp.o)
      cybozu::Exception::~Exception() in libbls384_256.a(fp.o)
  "___cxa_free_exception", referenced from:
      cybozu::RandomGenerator::RandomGenerator() in libbls384_256.a(bls_c384_256.o)
      cybozu::RandomGenerator::RandomGenerator() in libbls384_256.a(fp.o)
  "std::__1::thread::join()", referenced from:
      _blsMultiVerify in libbls384_256.a(bls_c384_256.o)
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::basic_string(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      cybozu::RandomGenerator::RandomGenerator() in libbls384_256.a(bls_c384_256.o)
      cybozu::RandomGenerator::RandomGenerator() in libbls384_256.a(fp.o)
  "std::terminate()", referenced from:
      _blsMultiVerify in libbls384_256.a(bls_c384_256.o)
  "std::__1::thread::~thread()", referenced from:
      _blsMultiVerify in libbls384_256.a(bls_c384_256.o)
  "___gxx_personality_v0", referenced from:
      mcl::FpT<mcl::bn::local::FrTag, 256ul>::setByCSPRNG(bool*, mcl::fp::RandGen) in libbls384_256.a(bls_c384_256.o)
      mcl::FpT<mcl::bn::local::FpTag, 384ul>::setByCSPRNG(bool*, mcl::fp::RandGen) in libbls384_256.a(bls_c384_256.o)
      mcl::fp::RandGen::setRandFunc(void*, unsigned int (*)(void*, void*, unsigned int)) in libbls384_256.a(bls_c384_256.o)
      _blsMultiVerify in libbls384_256.a(bls_c384_256.o)
      mcl::fp::RandGen::getDefaultRandGen() in libbls384_256.a(bls_c384_256.o)
      cybozu::RandomGenerator::RandomGenerator() in libbls384_256.a(bls_c384_256.o)
      std::__1::thread::thread<void (&)(mclBnGT*, blsSignature*, blsSignature const*, blsPublicKey const*, char const*, unsigned long, char const*, unsigned long, unsigned long), mclBnGT*, blsSignature*, blsSignature const*&, blsPublicKey const*&, char const*&, unsigned long&, char const*&, unsigned long&, unsigned long&, void>(void (&)(mclBnGT*, blsSignature*, blsSignature const*, blsPublicKey const*, char const*, unsigned long, char const*, unsigned long, unsigned long), mclBnGT*&&, blsSignature*&&, blsSignature const*&, blsPublicKey const*&, char const*&, unsigned long&, char const*&, unsigned long&, unsigned long&) in libbls384_256.a(bls_c384_256.o)
      ...
  "operator delete(void*)", referenced from:
      cybozu::RandomGenerator::RandomGenerator() in libbls384_256.a(bls_c384_256.o)
      cybozu::Exception::~Exception() in libbls384_256.a(bls_c384_256.o)
      cybozu::Exception::~Exception() in libbls384_256.a(bls_c384_256.o)
      std::__1::thread::thread<void (&)(mclBnGT*, blsSignature*, blsSignature const*, blsPublicKey const*, char const*, unsigned long, char const*, unsigned long, unsigned long), mclBnGT*, blsSignature*, blsSignature const*&, blsPublicKey const*&, char const*&, unsigned long&, char const*&, unsigned long&, unsigned long&, void>(void (&)(mclBnGT*, blsSignature*, blsSignature const*, blsPublicKey const*, char const*, unsigned long, char const*, unsigned long, unsigned long), mclBnGT*&&, blsSignature*&&, blsSignature const*&, blsPublicKey const*&, char const*&, unsigned long&, char const*&, unsigned long&, unsigned long&) in libbls384_256.a(bls_c384_256.o)
      void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(mclBnGT*, blsSignature*, blsSignature const*, blsPublicKey const*, char const*, unsigned long, char const*, unsigned long, unsigned long), mclBnGT*, blsSignature*, blsSignature const*, blsPublicKey const*, char const*, unsigned long, char const*, unsigned long, unsigned long> >(void*) in libbls384_256.a(bls_c384_256.o)
      cybozu::RandomGenerator::RandomGenerator() in libbls384_256.a(fp.o)
      cybozu::Exception::~Exception() in libbls384_256.a(fp.o)
      ...
  "___cxa_guard_acquire", referenced from:
      mcl::FpT<mcl::bn::local::FrTag, 256ul>::setByCSPRNG(bool*, mcl::fp::RandGen) in libbls384_256.a(bls_c384_256.o)
      mcl::FpT<mcl::bn::local::FpTag, 384ul>::setByCSPRNG(bool*, mcl::fp::RandGen) in libbls384_256.a(bls_c384_256.o)
      mcl::fp::RandGen::setRandFunc(void*, unsigned int (*)(void*, void*, unsigned int)) in libbls384_256.a(bls_c384_256.o)
      mcl::fp::RandGen::getDefaultRandGen() in libbls384_256.a(bls_c384_256.o)
      mcl::VintT<mcl::vint::FixedBuffer<unsigned long long, 1024ul> >::setRand(bool*, mcl::VintT<mcl::vint::FixedBuffer<unsigned long long, 1024ul> > const&, mcl::fp::RandGen) in libbls384_256.a(fp.o)
      mcl::fp::RandGen::getDefaultRandGen() in libbls384_256.a(fp.o)
  "___cxa_guard_release", referenced from:
      mcl::FpT<mcl::bn::local::FrTag, 256ul>::setByCSPRNG(bool*, mcl::fp::RandGen) in libbls384_256.a(bls_c384_256.o)
      mcl::FpT<mcl::bn::local::FpTag, 384ul>::setByCSPRNG(bool*, mcl::fp::RandGen) in libbls384_256.a(bls_c384_256.o)
      mcl::fp::RandGen::setRandFunc(void*, unsigned int (*)(void*, void*, unsigned int)) in libbls384_256.a(bls_c384_256.o)
      mcl::fp::RandGen::getDefaultRandGen() in libbls384_256.a(bls_c384_256.o)
      mcl::VintT<mcl::vint::FixedBuffer<unsigned long long, 1024ul> >::setRand(bool*, mcl::VintT<mcl::vint::FixedBuffer<unsigned long long, 1024ul> > const&, mcl::fp::RandGen) in libbls384_256.a(fp.o)
      mcl::fp::RandGen::getDefaultRandGen() in libbls384_256.a(fp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by hopwesley** [comment]
Undefined symbols for architecture arm64:
  "vtable for __cxxabiv1::__si_class_type_info", referenced from:
      typeinfo for cybozu::Exception in libbls384_256.a(bls_c384_256.o)
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "typeinfo for std::exception", referenced from:
      typeinfo for cybozu::Exception in libbls384_256.a(bls_c384_256.o)
  "std::__1::__thread_local_data()", referenced from:
      void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(mclBnGT*, blsSignature*, blsSignature const*, blsPublicKey const*, char const*, unsigned long, char const*, unsigned long, unsigned long), mclBnGT*, blsSignature*, blsSignature const*, blsPublicKey const*, char const*, unsigned long, char const*, unsigned long, unsigned long> >(void*) in libbls384_256.a(bls_c384_256.o)
  "std::__1::__thread_struct::__thread_struct()", referenced from:
      std::__1::thread::thread<void (&)(mclBnGT*, blsSignature*, blsSignature const*, blsPublicKey const*, char const*, unsigned long, char const*, unsigned long, unsigned long), mclBnGT*, blsSignature*, blsSignature const*&, blsPublicKey const*&, char const*&, unsigned long&, char const*&, unsigned long&, unsigned long&, void>(void (&)(mclBnGT*, blsSignature*, blsSignature const*, blsPublicKey const*, char const*, unsigned long, char const*, unsigned long, unsigned long), mclBnGT*&&, blsSignature*&&, blsSignature const*&, blsPublicKey const*&, char const*&, unsigned long&, char const*&, unsigned long&, unsigned long&) in libbls384_256.a(bls_c384_256.o)
  "operator new(unsigned long)", referenced from:
      std::__1::thread::thread<void (&)(mclBnGT*, blsSignature*, blsSignature const*, blsPublicKey const*, char const*, unsigned long, char const*, unsigned long, unsigned long), mclBnGT*, blsSignature*, blsSignature const*&, blsPublicKey const*&, char const*&, unsigned long&, char const*&, unsigned long&, unsigned long&, void>(void (&)(mclBnGT*, blsSignature*, blsSignature const*, blsPublicKey const*, char const*, unsigned long, char const*, unsigned long, unsigned long), mclBnGT*&&, blsSignature*&&, blsSignature const*&, blsPublicKey const*&, char const*&, unsigned long&, char const*&, unsigned long&, unsigned long&) in libbls384_256.a(bls_c384_256.o)
  "std::__1::__thread_struct::~__thread_struct()", referenced from:
      std::__1::thread::thread<void (&)(mclBnGT*, blsSignature*, blsSignature const*, blsPublicKey const*, char const*, unsigned long, char const*, unsigned long, unsigned long), mclBnGT*, blsSignature*, blsSignature const*&, blsPublicKey const*&, char const*&, unsigned long&, char const*&, unsigned long&, unsigned long&, void>(void (&)(mclBnGT*, blsSignature*, blsSignature const*, blsPublicKey const*, char const*, unsigned long, char const*, unsigned long, unsigned long), mclBnGT*&&, blsSignature*&&, blsSignature const*&, blsPublicKey const*&, char const*&, unsigned long&, char const*&, unsigned long&, unsigned long&) in libbls384_256.a(bls_c384_256.o)
      void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(mclBnGT*, blsSignature*, blsSignature const*, blsPublicKey const*, char const*, unsigned long, char const*, unsigned long, unsigned long), mclBnGT*, blsSignature*, blsSignature const*, blsPublicKey const*, char const*, unsigned long, char const*, unsigned long, unsigned long> >(void*) in libbls384_256.a(bls_c384_256.o)
  "___cxa_allocate_exception", referenced from:
      cybozu::RandomGenerator::RandomGenerator() in libbls384_256.a(bls_c384_256.o)
      cybozu::RandomGenerator::RandomGenerator() in libbls384_256.a(fp.o)
  "___cxa_throw", referenced from:
      cybozu::RandomGenerator::RandomGenerator() in libbls384_256.a(bls_c384_256.o)
      cybozu::RandomGenerator::RandomGenerator() in libbls384_256.a(fp.o)
  "std::__1::__throw_system_error(int, char const*)", referenced from:
      std::__1::thread::thread<void (&)(mclBnGT*, blsSignature*, blsSignature const*, blsPublicKey const*, char const*, unsigned long, char const*, unsigned long, unsigned long), mclBnGT*, blsSignature*, blsSignature const*&, blsPublicKey const*&, char const*&, unsigned long&, char const*&, unsigned long&, unsigned long&, void>(void (&)(mclBnGT*, blsSignature*, blsSignature const*, blsPublicKey const*, char const*, unsigned long, char const*, unsigned long, unsigned long), mclBnGT*&&, blsSignature*&&, blsSignature const*&, blsPublicKey const*&, char const*&, unsigned long&, char const*&, unsigned long&, unsigned long&) in libbls384_256.a(bls_c384_256.o)
  "___cxa_guard_abort", referenced from:
      mcl::FpT<mcl::bn::local::FrTag, 256ul>::setByCSPRNG(bool*, mcl::fp::RandGen) in libbls384_256.a(bls_c384_256.o)
      mcl::FpT<mcl::bn::local::FpTag, 384ul>::setByCSPRNG(bool*, mcl::fp::RandGen) in libbls384_256.a(bls_c384_256.o)
      mcl::fp::RandGen::setRandFunc(void*, unsigned int (*)(void*, void*, unsigned int)) in libbls384_256.a(bls_c384_256.o)
      mcl::fp::RandGen::getDefaultRandGen() in libbls384_256.a(bls_c384_256.o)
      mcl::VintT<mcl::vint::FixedBuffer<unsigned long long, 1024ul> >::setRand(bool*, mcl::VintT<mcl::vint::FixedBuffer<unsigned long long, 1024ul> > const&, mcl::fp::RandGen) in libbls384_256.a(fp.o)
      mcl::fp::RandGen::getDefaultRandGen() in libbls384_256.a(fp.o)
  "std::exception::~exception()", referenced from:
      cybozu::RandomGenerator::RandomGenerator() in libbls384_256.a(bls_c384_256.o)
      cybozu::Exception::~Exception() in libbls384_256.a(bls_c384_256.o)
      cybozu::Exception::~Exception() in libbls384_256.a(bls_c384_256.o)
      cybozu::RandomGenerator::RandomGenerator() in libbls384_256.a(fp.o)
      cybozu::Exception::~Exception() in libbls384_256.a(fp.o)
      cybozu::Exception::~Exception() in libbls384_256.a(fp.o)
  "___cxa_free_exception", referenced from:
      cybozu::RandomGenerator::RandomGenerator() in libbls384_256.a(bls_c384_256.o)
      cybozu::RandomGenerator::RandomGenerator() in libbls384_256.a(fp.o)
  "std::__1::thread::join()", referenced from:
      _blsMultiVerify in libbls384_256.a(bls_c384_256.o)
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::basic_string(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      cybozu::RandomGenerator::RandomGenerator() in libbls384_256.a(bls_c384_256.o)
      cybozu::RandomGenerator::RandomGenerator() in libbls384_256.a(fp.o)
  "std::terminate()", referenced from:
      _blsMultiVerify in libbls384_256.a(bls_c384_256.o)
  "std::__1::thread::~thread()", referenced from:
      _blsMultiVerify in libbls384_256.a(bls_c384_256.o)
  "___gxx_personality_v0", referenced from:
      mcl::FpT<mcl::bn::local::FrTag, 256ul>::setByCSPRNG(bool*, mcl::fp::RandGen) in libbls384_256.a(bls_c384_256.o)
      mcl::FpT<mcl::bn::local::FpTag, 384ul>::setByCSPRNG(bool*, mcl::fp::RandGen) in libbls384_256.a(bls_c384_256.o)
      mcl::fp::RandGen::setRandFunc(void*, unsigned int (*)(void*, void*, unsigned int)) in libbls384_256.a(bls_c384_256.o)
      _blsMultiVerify in libbls384_256.a(bls_c384_256.o)
      mcl::fp::RandGen::getDefaultRandGen() in libbls384_256.a(bls_c384_256.o)
      cybozu::RandomGenerator::RandomGenerator() in libbls384_256.a(bls_c384_256.o)
      std::__1::thread::thread<void (&)(mclBnGT*, blsSignature*, blsSignature const*, blsPublicKey const*, char const*, unsigned long, char const*, unsigned long, unsigned long), mclBnGT*, blsSignature*, blsSignature const*&, blsPublicKey const*&, char const*&, unsigned long&, char const*&, unsigned long&, unsigned long&, void>(void (&)(mclBnGT*, blsSignature*, blsSignature const*, blsPublicKey const*, char const*, unsigned long, char const*, unsigned long, unsigned long), mclBnGT*&&, blsSignature*&&, blsSignature const*&, blsPublicKey const*&, char const*&, unsigned long&, char const*&, unsigned long&, unsigned long&) in libbls384_256.a(bls_c384_256.o)
      ...
  "operator delete(void*)", referenced from:
      cybozu::RandomGenerator::RandomGenerator() in libbls384_256.a(bls_c384_256.o)
      cybozu::Exception::~Exception() in libbls384_256.a(bls_c384_256.o)
      cybozu::Exception::~Exception() in libbls384_256.a(bls_c384_256.o)
      std::__1::thread::thread<void (&)(mclBnGT*, blsSignature*, blsSignature const*, blsPublicKey const*, char const*, unsigned long, char const*, unsigned long, unsigned long), mclBnGT*, blsSignature*, blsSignature const*&, blsPublicKey const*&, char const*&, unsigned long&, char const*&, unsigned long&, unsigned long&, void>(void (&)(mclBnGT*, blsSignature*, blsSignature const*, blsPublicKey const*, char const*, unsigned long, char const*, unsigned long, unsigned long), mclBnGT*&&, blsSignature*&&, blsSignature const*&, blsPublicKey const*&, char const*&, unsigned long&, char const*&, unsigned long&, unsigned long&) in libbls384_256.a(bls_c384_256.o)
      void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(mclBnGT*, blsSignature*, blsSignature const*, blsPublicKey const*, char const*, unsigned long, char const*, unsigned long, unsigned long), mclBnGT*, blsSignature*, blsSignature const*, blsPublicKey const*, char const*, unsigned long, char const*, unsigned long, unsigned long> >(void*) in libbls384_256.a(bls_c384_256.o)
      cybozu::RandomGenerator::RandomGenerator() in libbls384_256.a(fp.o)
      cybozu::Exception::~Exception() in libbls384_256.a(fp.o)
      ...
  "___cxa_guard_acquire", referenced from:
      mcl::FpT<mcl::bn::local::FrTag, 256ul>::setByCSPRNG(bool*, mcl::fp::RandGen) in libbls384_256.a(bls_c384_256.o)
      mcl::FpT<mcl::bn::local::FpTag, 384ul>::setByCSPRNG(bool*, mcl::fp::RandGen) in libbls384_256.a(bls_c384_256.o)
      mcl::fp::RandGen::setRandFunc(void*, unsigned int (*)(void*, void*, unsigned int)) in libbls384_256.a(bls_c384_256.o)
      mcl::fp::RandGen::getDefaultRandGen() in libbls384_256.a(bls_c384_256.o)
      mcl::VintT<mcl::vint::FixedBuffer<unsigned long long, 1024ul> >::setRand(bool*, mcl::VintT<mcl::vint::FixedBuffer<unsigned long long, 1024ul> > const&, mcl::fp::RandGen) in libbls384_256.a(fp.o)
      mcl::fp::RandGen::getDefaultRandGen() in libbls384_256.a(fp.o)
  "___cxa_guard_release", referenced from:
      mcl::FpT<mcl::bn::local::FrTag, 256ul>::setByCSPRNG(bool*, mcl::fp::RandGen) in libbls384_256.a(bls_c384_256.o)
      mcl::FpT<mcl::bn::local::FpTag, 384ul>::setByCSPRNG(bool*, mcl::fp::RandGen) in libbls384_256.a(bls_c384_256.o)
      mcl::fp::RandGen::setRandFunc(void*, unsigned int (*)(void*, void*, unsigned int)) in libbls384_256.a(bls_c384_256.o)
      mcl::fp::RandGen::getDefaultRandGen() in libbls384_256.a(bls_c384_256.o)
      mcl::VintT<mcl::vint::FixedBuffer<unsigned long long, 1024ul> >::setRand(bool*, mcl::VintT<mcl::vint::FixedBuffer<unsigned long long, 1024ul> > const&, mcl::fp::RandGen) in libbls384_256.a(fp.o)
      mcl::fp::RandGen::getDefaultRandGen() in libbls384_256.a(fp.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by herumi** [comment]
How about https://github.com/herumi/bls-eth-go-binary/commit/53147ec2b0e0c607a25827b760055df411d016a7 ?
