### ISSUE TITLE
s390x test failures

### ISSUE THREAD

**Issue by e-desouza** [herumi/bls-eth-go-binary#43]
Thank you for the work on mcl s390x support! I noticed a s390x patch for this project and tried building (which works) but tests fails [(gist of logs)](https://gist.github.com/e-desouza/2da9a421e457b0aecb49fe07d526d730). Do I need to turn on special build flags?

**Comment by herumi** [comment]
I verified the failure.
The error is from `makeMultiSig(400)`.
`makeMultiSig(200)` is okay. I'll search the reason.

**Comment by herumi** [comment]
It returned errno = 42(EMFILE). By removing "-fno-threadsafe-statics", the error does not occur.
https://github.com/herumi/bls-eth-go-binary/commit/31246bfa8ac4c6073c3e95a683877eab08b6134c

**Comment by e-desouza** [comment]
Yes that worked!

Ran the test on 2 systems to compare and was wondering why one had -16 and other had -6.  The middle column seems random, but those numbers seem constant across runs.

```
BenchmarkPairing-16                 	    2031	    565680 ns/op
BenchmarkSignHash-16                	    2476	    429755 ns/op
BenchmarkVerifyHash-16              	    1206	   1007527 ns/op
BenchmarkVerifyAggreageteHash-16    	      49	  22245508 ns/op
BenchmarkNaieveMultiVerify-16       	       3	 391130520 ns/op
BenchmarkMultiVerify-16             	      40	  29863456 ns/op
```
```
BenchmarkPairing-6                           417           2985097 ns/op
BenchmarkSignHash-6                          447           2327140 ns/op
BenchmarkVerifyHash-6                        194           5463469 ns/op
BenchmarkVerifyAggreageteHash-6                9         130650396 ns/op
BenchmarkNaieveMultiVerify-6                   1        2168997593 ns/op
BenchmarkMultiVerify-6                         4         422206576 ns/op
```

**Comment by herumi** [comment]
>was wondering why one had -16 and other had -6.

The behavior is golang specification.
The numbers are bigger on a faster machine.
https://golang.org/pkg/testing/#hdr-Benchmarks

**Comment by e-desouza** [comment]
Ah ! It's the core count. One box was 6 vCPUs the other was 16 vCPUs. Would dividing those numbers by the core count give an accurate ns/op per core number (and then lower ns/op is better?)
