### ISSUE TITLE
Arm64 Archive in Linux is missing `blsSetGeneratorOfPublicKey` 

### ISSUE THREAD

**Issue by nisdas** [herumi/bls-eth-go-binary#44]
The archive https://github.com/herumi/bls-eth-go-binary/blob/master/bls/lib/linux/arm64/libbls384_256.a is missing the 
`blsSetGeneratorOfPublicKey` symbol, therefore any arm64 users on linux are unable to compile and run it.

**Comment by herumi** [comment]
I've updated bls/mcl and built all libraries.
Could you try https://github.com/herumi/bls-eth-go-binary/commit/f657a496e5b058ed657af42b049fbc8d3c89ee7b ?
If it is okay, then I'll push it into master.

**Comment by nisdas** [comment]
This commit works for me ! Thanks for the quick fix.

**Comment by herumi** [comment]
Thank you for the verification. I've merged it into master.
