### ISSUE TITLE
no member named 'move' in namespace 'std'

### ISSUE THREAD

**Issue by hopwesley** [herumi/bls-eth-go-binary#45]
rc/bls/mcl/include/mcl/vint.hpp:1147:10: error: no member named 'move' in namespace 'std'; did you mean 'mod'?
                buf_ = std::move(rhs.buf_);
                       ^~~~~~~~~
                       mod
src/bls/mcl/include/mcl/vint.hpp:1479:14: note: 'mod' declared here
        static void mod(VintT& r, const VintT& x, const VintT& y)
                    ^
src/bls/mcl/include/mcl/vint.hpp:1147:28: error: too few arguments to function call, expected 3, have 1
                buf_ = std::move(rhs.buf_);
                            ~~~~         ^

**Comment by hopwesley** [comment]
hyperorchid@localhost bls-eth-go-binary % make ios
/Applications/Xcode.app/Contents/Developer/usr/bin/make each_ios PLATFORM="iPhoneOS" ARCH=armv7 BIT=32 UNIT=4
Building iOS armv7 BIT=32 UNIT=4
IOS_CFLAGS=-fembed-bitcode -fno-common -DPIC -fPIC -Dmcl_EXPORTS -fno-exceptions -fno-rtti -fno-threadsafe-statics -fno-stack-protector -DCYBOZU_DONT_USE_EXCEPTION -DCYBOZU_DONT_USE_STRING -DMCL_USE_VINT -DMCL_VINT_FIXED_BUFFER -DMCL_DONT_USE_OPENSSL -DMCL_DONT_USE_XBYAK -DMCL_LLVM_BMI2=0 -DMCL_USE_LLVM=1 -std=c++11 -Wall -Wextra -Wformat=2 -Wcast-qual -Wcast-align -Wwrite-strings -Wfloat-equal -Wpointer-arith -O3 -DNDEBUG -DBLS_ETH -DBLS_SWAP_G -I src/bls/mcl/include -I src/bls/include -DMCL_SIZEOF_UNIT=4
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch armv7 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -mios-version-min=7.0 -fembed-bitcode -fno-common -DPIC -fPIC -Dmcl_EXPORTS -fno-exceptions -fno-rtti -fno-threadsafe-statics -fno-stack-protector -DCYBOZU_DONT_USE_EXCEPTION -DCYBOZU_DONT_USE_STRING -DMCL_USE_VINT -DMCL_VINT_FIXED_BUFFER -DMCL_DONT_USE_OPENSSL -DMCL_DONT_USE_XBYAK -DMCL_LLVM_BMI2=0 -DMCL_USE_LLVM=1 -std=c++11 -Wall -Wextra -Wformat=2 -Wcast-qual -Wcast-align -Wwrite-strings -Wfloat-equal -Wpointer-arith -O3 -DNDEBUG -DBLS_ETH -DBLS_SWAP_G -I src/bls/mcl/include -I src/bls/include -DMCL_SIZEOF_UNIT=4 -c src/bls/mcl/src/fp.cpp -o ios/armv7/fp.o
In file included from src/bls/mcl/src/fp.cpp:1:
In file included from src/bls/mcl/include/mcl/op.hpp:9:
In file included from src/bls/mcl/include/mcl/gmp_util.hpp:34:
src/bls/mcl/include/mcl/vint.hpp:1147:10: error: no member named 'm

**Comment by herumi** [comment]
The previous clang can compile it, but clang 12.0.5 can't compile it.
Could you try this patch https://github.com/herumi/bls-eth-go-binary/commit/b5186ba08dc7b1d7381ff5ea3f1d0d0ad3d02986 ?
