### ISSUE TITLE
Android project import steps

### ISSUE THREAD

**Issue by uszkaisandor** [herumi/bls-eth-go-binary#47]
Please include project import steps as well for Android platform. I have the built folders for 3 ABI's but I'm not sure how to make it accessible from an Android project. 

I've added the "arm64-v8a", "armeabi-v7a", "x86_64" folders to my app's "src/main/jniLibs" folder.

What should I do next?

**Comment by herumi** [comment]
I provide a Java binding at https://github.com/herumi/bls/tree/master/ffi/java .
I'm not familiar with Android projects, but I think that it's okay to make shared libraries according to https://github.com/herumi/bls-eth-go-binary#android, and add those files to the project setting.

**Comment by herumi** [comment]
https://github.com/herumi/bls-eth-go-binary/releases/
