### ISSUE TITLE
Trying to use for Dash blockchain

### ISSUE THREAD

**Issue by ant013** [herumi/bls-eth-go-binary#49]
I trying to build library for iOS to use with Dash blockchains. They use bls-signature for verify masternodes messages.
Firstly, I check sample code and can serialize/deserialize public key for ETH like:

hex.DecodeString("841c5235ec7f4eed02b3f3bb60622d3ed0aba74016f4850c6d7c962656a4b78d72a15caeef62dfe656d03990590c0026")
pk.Deserialize(pubByte)
pk.SerializeToHexStr()

and its working nice. But for publickey hex form Dash masternodes it returns:
"800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
 
[Test Vector]
pubKey: "141d89e211c93bee9f4cb26e4bd1fa530798dc1cc27e545c0e096aec9d913ba2cae572b339aaab612a0bb2f60dd71ceb"
signature: "0cace6526d0f27e7b969700877796fce5d0a441281d952197eee051385b22c7b9010981cecd19986fc185aa65ac8d82b0c8ba2e0f2cab703f4cd9c3079cc53b78d947bc6d8cc6b05f87fcffea778a05df53f0340d6d0c4f9de182016df8452fe"
message: "764ffc3658c9e40ebed871d60eb92add480d437973d59038c37d6e55dda35461"

I thinks that Dash using another parameters for BLS, but can't realize it.
Is it possible to configure BLS for using with Dash as iOS framework?
Thanks!

**Comment by herumi** [comment]
mcl/bls supports many mode, so could you ask the Dash developer what parameters they use?

**Comment by ant013** [comment]
There are from official document:
https://datatracker.ietf.org/doc/draft-irtf-cfrg-bls-signature/

4.2.1.  Basic

   BLS_SIG_BLS12381G1_XMD:SHA-256_SSWU_RO_NUL_ is defined as follows:

   *  SC: basic

   *  SV: minimal-signature-size

   *  EC: BLS12-381, as defined in Appendix A.

   *  H: SHA-256

   *  hash_to_point: BLS12381G1_XMD:SHA-256_SSWU_RO_ with the ASCII-
      encoded domain separation tag

      BLS_SIG_BLS12381G1_XMD:SHA-256_SSWU_RO_NUL_

   BLS_SIG_BLS12381G2_XMD:SHA-256_SSWU_RO_NUL_ is identical to
   BLS_SIG_BLS12381G1_XMD:SHA-256_SSWU_RO_NUL_, except for the following
   parameters:

Boneh, et al.           Expires 18 December 2022               [Page 22]
Internet-Draft                BLS-signature                    June 2022

   *  SV: minimal-pubkey-size

   *  hash_to_point: BLS12381G2_XMD:SHA-256_SSWU_RO_ with the ASCII-
      encoded domain separation tag

      BLS_SIG_BLS12381G2_XMD:SHA-256_SSWU_RO_NUL_

**Comment by herumi** [comment]
>But for publickey hex form Dash masternodes it returns:
>"800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"

I don't know what way Dash encodes a public key. Could you ask them for the pointer to the source code of PublicKey::deserialize(byte[])?

**Comment by ant013** [comment]
Dash use legacy 'old' style for publicKey and Signature. So i found convertation  algorythm.
