### ISSUE TITLE
Linker complains about executable stack on Linux

### ISSUE THREAD

**Issue by gsora** [herumi/bls-eth-go-binary#52]
When compiling a software based on this library on a recent enough Linux system (like the latest ubuntu), the following message appears:

```
# github.com/herumi/bls-go-binary/bls.test
/usr/bin/ld: warning: bint-x64-amd64.o: missing .note.GNU-stack section implies executable stack
/usr/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
```

**Comment by herumi** [comment]
How about pass a option `-z noexecstack` to the linker?

**Comment by gsora** [comment]
That should fix it.

If you’re able to provide a branch with some test code, I can try on my machine.

**Comment by herumi** [comment]
Could you please tell me the version of a compiler and compiler options to show the warnings?

**Comment by gsora** [comment]
I’m using GCC 12 and Go 1.19. Although, the linker is giving the error I’m reporting: it happens at runtime.

**Comment by herumi** [comment]
I removed the warning in the latest version.
cf. https://github.com/herumi/mcl/commit/3c0d7b064b9c36dbad7ed48426fdaa03022e2245
