### ISSUE TITLE
Going from v1.29.1 to v1.31.0 broke Windows builds with `ERR Init curve=5` on startup

### ISSUE THREAD

**Issue by remyroy** [herumi/bls-eth-go-binary#54]
It seems like recent updates broke Windows builds with a startup error on *curve=5*. See https://github.com/wealdtech/ethdo/issues/111

**Comment by herumi** [comment]
Could you tell me what version of Go, what CPU environment, and what error?

**Comment by remyroy** [comment]
This is with go version `go1.21.3 windows/amd64`, on AMD64, on Windows 10 (Version 22H2, Build 19045.3570), using GCC 13.2.0 (with POSIX threads) + LLVM/Clang/LLD/LLDB 16.0.6 + MinGW-w64 11.0.1 (UCRT) - release from https://winlibs.com/.

During startup, the only error message shown is:

```
ERR Init curve=5
```

and the program exit.

**Comment by herumi** [comment]
Can you `make clean && make` in the directory `bls-eth-go-binary` and retry the test?
If the compiled binary runs well, the building way in bls-eth-go-binary/GitHub Action may be wrong.

**Comment by herumi** [comment]
Oh, I found the reason.
I've missed setting ETH_CFLAGS on building a Windows binary. Please wait a moment.

**Comment by remyroy** [comment]
Updating to v1.32.1 fixed my issue. Thanks.

**Comment by herumi** [comment]
Thank you for the verification.
