### ISSUE TITLE
Is `-lstdc++` needed during linking?

### ISSUE THREAD

**Issue by gsora** [herumi/bls-eth-go-binary#58]
Hi!

Is `-lstdc++` [LDFLAGS](https://github.com/herumi/bls-eth-go-binary/blob/master/bls/link.go#L7) flag needed for this library to work?

I just tried compiling the example file without it, and it appears to work just fine.

I'm wondering because its presence makes cross-compiling from Linux to macOS quite a bit painful.

Thanks!

**Comment by herumi** [comment]
It is necessary on x64 Linux. I'll change `bls/link.go` not to link it on M1 mac.

**Comment by herumi** [comment]
Does [this patch](https://github.com/herumi/bls-eth-go-binary/commit/0e78274cb9ea5cb6aa7134a167cbf77a8f682780) work on your architecture?

**Comment by gsora** [comment]
Hey! Re-opening this issue to communicate that on darwin arm64 the issue is now fixed.

Do you believe we can get rid of `-lstdc++` on darwin amd64 as well?

Thank you!

**Comment by herumi** [comment]
It is unnecessary if it runs well without `-lstdc++`. I'll remove it in the next version.

**Comment by gsora** [comment]
I did not test this case, but by logic if it works without it on arm64 I don’t see why it shouldn’t on amd64 as well.

**Comment by herumi** [comment]
Different source code is used for arm64 and amd64. Even if it is okay on macOS, I don't know if it is the same elsewhere without trying. In fact, on Windows, `-lstdc++` is required on amd64.

**Comment by gsora** [comment]
Yeah I can see that being an issue. 

Do you have an ETA for the release of a version embedding a fix?

**Comment by herumi** [comment]
I released https://github.com/herumi/bls-eth-go-binary/releases/tag/v1.35.0
