### ISSUE TITLE
Random generation

### ISSUE THREAD

**Issue by hermanjunge** [herumi/bls-eth-go-binary#6]
Hi,

I'm using the library for a bulk key generator in go.

After some quick research, I've found the method `SetByCSPRNG()` to leverage from `setRand()` at https://github.com/herumi/mcl/blob/e0f7f5d0735f9214c157b4b163b3f048375e05c7/include/mcl/she.hpp#L665

**Question: what is the source of entropy of this latter method?**

**Comment by herumi** [comment]
setRand() finally calls `/dev/urandom` on Linux from https://github.com/herumi/mcl/blob/master/include/cybozu/random_generator.hpp .
You can use "cryoto/rand.Reader" by calling [SetRandFunc(rand.Reader)](https://github.com/herumi/bls-eth-go-binary/blob/master/bls/bls.go#L859).
cf. https://github.com/herumi/bls/blob/master/ffi/go/bls/bls_test.go#L478

**Comment by hermanjunge** [comment]
Thank you.
